---
name: Build and test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "This job's status is ${{ job.status }}."
      - name: Setup NodeJS with cache
        uses: dreamcodez/dead-simple-nodejs@1
        with:
          NODE_VERSION: 20.9.0
      - name: install dependencies
        run: yarn install
        working-directory: webapp
      - name: lint
        run: yarn lint
        working-directory: webapp