---
name: Build and test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "This job's status is ${{ job.status }}."
      - name: Setup NodeJS with cache
        uses: dreamcodez/dead-simple-nodejs@1
        with:
          NODE_VERSION: 20.9.0
      - name: install dependencies
        run: yarn install
        working-directory: webapp
      - name: lint
        run: yarn lint
        working-directory: webapp
      - name: Log in to dockerHub
        uses: docker/login-action@v2
        with:
          username: tomas.boone@student.hogent.be
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/webapp:latest